package App.syntacticAnalysis;

public enum NodeType {

    STATEMENT,
    SET_TITLE,
    SET_HEALTH,
    SET_INVENTORY_SLOT,
    ADD_LOCATION,
    ADD_ITEM,
    ADD_CHARACTER,
    SET_HEALTH_ACTION,
    SET_ITEM_ACTION,
    SET_CHARACTER_ACTION,
    SET_ITEM_CONDITION,
    SET_CHARACTER_CONDITION,
    OPTION_DEFINITION,
}
