package App.syntacticAnalysis;

public enum NodeType {

    STATEMENT,
    SET_TITLE,
    SET_HEALTH,
    SET_INVENTORY,
    SET_INVENTORY_SLOT,
    ADD_LOCATION,
    ADD_ITEM,
    ADD_CHARACTER,
    SET_ACTION,
    SET_ACTIONS,
    SET_ACTION_KIND,
    SET_ACTION_OP,
    SET_CONDITION,
    SET_CONDITION_KIND,
    SET_CONDITIONS,
    STR,
    INT,
    VAR,
    OPTION_DEFINITION,
}
